### ISSUE TITLE
Cannot save headers.

### ISSUE THREAD

**Issue by optimistsc** [jarrodek/ChromeRestClient#352]
Cannot save headers. 

When selected saved project. 'Content-Type' reset to 'application/x-www-form-urlencoded'

**Comment by Evotica** [comment]
In my case all the headers stored in my projects became cleared. I think this happened yesterday. If I try overwrite them, the headers are still empty when I load them

**Comment by jarrodek** [comment]
Today was an update fixing the problem: #347 #345 #346 which are related. Current CWS version is 4.5.1. Do you have this version and and it's working already?

**Comment by justinhelmer** [comment]
I can confirm this was fixed via the `hotfixes` called out by @jarrodek. Grab the updates and you will be good-to-go.

**Comment by optimistsc** [comment]
Issue was solved. thx.

**Comment by Evotica** [comment]
Still does not work for me. chrome://extensions/ says I have  4.5.1-stable.0.
About says I have Application version: 4.5.0 Stable

Saving to outside project seems to save the headers.

Saving as new with new name or trying to overwrite into existing project does not save the headers.

**Comment by jarrodek** [comment]
I just run every test case I can think about and it works just fine. At least in 4.5.0. Is there any database error in the console? 
Versions are messed up since i changed bump system. I have to fix it but it's not so important right now.

**Comment by justinhelmer** [comment]
@Evotica do you have `CodeMirror` enabled? You may want to try switching that off temporarily to see if it has an impact on your results. @jarrodek is already aware of a [related issue](https://github.com/jarrodek/ChromeRestClient/issues/354) and may actually be related to what you are experiencing as well.

**Comment by Evotica** [comment]
I think my problem was a self caused problem by using Content-Type header a bit incorrectly.

I used Content-Type: text/xml in GET request when I should have used Accept: text/xml.
I'm not sure if it is allowed have Content-Type in a GET request.

Saving/Loading Accept header works with GET request both with and without a Project.
Saving/Loading Content-Type header works with GET request when saving outside Project. Loading into Project does not seem to work, or it works differently. It does not end up in the header box.

I did have core mirror enabled but turning it off didn't make any difference.

When exporting data it seems my possibly incorrect header did get saved.
```json
{
      "id" : 36,
      "encoding" : "application/x-www-form-urlencoded",
      "headers" : "Content-Type: text/xml; charset=utf-8",
      "method" : "GET",
      "name" : "my_name",
      "payload" : "",
      "project" : 3,
      "skipHeaders" : false,
      "skipHistory" : false,
      "skipMethod" : false,
      "skipParams" : false,
      "skipPath" : false,
      "skipPayload" : false,
      "skipProtocol" : false,
      "skipServer" : false,
      "time" : 1448610703696,
      "url" : "http://some.server.fi:8090/myurl",
      "driveId" : ""
}
```

Then when loading, it said
```
(-:-) 2016-01-15 10:05:05,343 [INFO ] Updating headers value: 

elements.js:16285 Setting changed CMH_ENABLED false
elements.js:16285 Setting changed CMP_ENABLED false
restclient.nocache.js:34 (-:-) 2016-01-15 10:06:09,545 [ERROR] Application error
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'a' of null
_.ub @ restclient.nocache.js:34D @ restclient.nocache.js:42Zk @ restclient.nocache.js:488Np @ restclient.nocache.js:104Zp @ restclient.nocache.js:105_.xc @ restclient.nocache.js:106Yp @ restclient.nocache.js:105(anonymous function) @ restclient.nocache.js:1033c @ restclient.nocache.js:105setTimeout (async)Wp @ restclient.nocache.js:105Up @ restclient.nocache.js:104WT @ restclient.nocache.js:987uQ @ restclient.nocache.js:802_.Zb @ restclient.nocache.js:535_.$b @ restclient.nocache.js:62_.Bc @ restclient.nocache.js:220_.zc @ restclient.nocache.js:134tu @ restclient.nocache.js:149rz @ restclient.nocache.js:220Az @ restclient.nocache.js:222_.Qc @ restclient.nocache.js:223_.Bc @ restclient.nocache.js:145_.zc @ restclient.nocache.js:134tu @ restclient.nocache.js:149su @ restclient.nocache.js:147_.Sc @ restclient.nocache.js:231mu @ restclient.nocache.js:145zA @ restclient.nocache.js:231(anonymous function) @ restclient.nocache.js:1033hashchange (async)Polymer._itemTap @ elements.js:16799handler @ elements.js:3056Polymer.Base._addFeature.fire @ elements.js:3903Gestures.fire @ elements.js:3393Gestures.register.forward @ elements.js:3684Gestures.register.click @ elements.js:3669Gestures.handleNative @ elements.js:3283
restclient.nocache.js:34 (-:-) 2016-01-15 10:06:09,587 [INFO ] Setting content type for payload encoding to text/xml; charset=utf-8

restclient.nocache.js:34 (-:-) 2016-01-15 10:07:00,774 [DEBUG] Restoring data for the same project as previous.

restclient.nocache.js:34 (-:-) 2016-01-15 10:07:00,784 [INFO ] Setting content type for payload encoding to text/xml; charset=utf-8

restclient.nocache.js:34 (-:-) 2016-01-15 10:07:00,792 [DEBUG] Restoring encoding to .application/x-www-form-urlencoded
```

I think the error line came when I opened the Projects view and it did not appear more than once.
If I understand the log right, it interpreted my stored header, and set the payload encoding accordingly, but it did not add that Content-Type as a header, as the header box remained empty.

Doing Send, and after receiving the response and looking at Request Headers, there was
```
X-DevTools-Emulate-Network-Conditions-Client-Id: F570EEA9-DFA0-47DE-BD76-A848F5DDE6DE
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Content-Type: text/plain; charset=utf-8
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,fi;q=0.6
```

So there was a Content-Type in the header but it was not the same that I had saved. text/xml had been changed into text/plain. The Response was in Content-type: text/plain;charset=utf-8.

When I manually entered my Content-Type for GET request before sending it, the Request Header in that case was

```
X-DevTools-Emulate-Network-Conditions-Client-Id: F570EEA9-DFA0-47DE-BD76-A848F5DDE6DE
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Content-type: text/xml
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,fi;q=0.6
```
In that case the response was in Content-type: text/xml;charset=utf-8, so the server responded with the same content type that the request had.

Saving and loading a GET request in Project with Accept: text/xml worked fine. The Request header in this case was

```
Accept: text/xml
X-DevTools-Emulate-Network-Conditions-Client-Id: F570EEA9-DFA0-47DE-BD76-A848F5DDE6DE
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,fi;q=0.6
```

and the response header contained only Transfer-encoding: chunked.

**Comment by jarrodek** [comment]
You right @Evotica 
The behaviour is actually expected in case of restoring project endpoint. When restoring from saved there's an issue because this header shouldn't be there.

First, GET requests do not carry payload so they don't need content-type headers. You can set it up and send it along with the request but it doesn't have sense because it do nothing. 
Reference: http://stackoverflow.com/questions/5661596/do-i-need-a-content-type-for-http-get-requests#comment27309342_16693884

Second, the header is not restored because of removing a line in file https://github.com/jarrodek/ChromeRestClient/blob/master/RestClient/src/org/rest/client/activity/RequestActivity.java#L1273
Earlier this line contained `requestView.setEncoding(request.getEncoding());`. This function is now used to support C-T header appearance.

Finally, the header is missing because there is a mechanism when you switch tabs (or restoring a request) it will add a C-T header with default value if the request can carry payload and if there wasn't C-T header already. Otherwise it will remove C-T from the list. 

Summering. The issue exist but it's not not restoring the header but actually restoring it.

**Comment by justinhelmer** [comment]
Thanks!
