### ISSUE TITLE
Content-Type missmatch hangs the client

### ISSUE THREAD

**Issue by TheLinker** [jarrodek/ChromeRestClient#438]
When i try to make request which content type does not match the result, the client hangs

## Expected outcome
Show the result, even if it doesn't parse.

## Actual outcome
the client shows the abort button and the request never completes (client side, the server is all ok)

## Versions
App: 6.12.14.108-beta
Chrome: 49.0.2623.110
Platform: Windows (7)

## Steps to reproduce
1. create a file (php in this example)
2. write this:
<pre>
header('Content-Type: application/json; charset=utf-8');
var_dump(1);
echo "\"a\"";
</pre>
3. create a request to this file and the request never completes.

**Comment by jarrodek** [comment]
It's probably one of the issues I have fixed in beta channel. You can check it following instructions from https://groups.google.com/forum/#!forum/advanced-rest-client-beta-channel

**Comment by TheLinker** [comment]
I have updated to version

App: 6.17.16.116-beta
Chrome: 49.0.2623.110
Platform: Windows (7)

And the problem still persists.
