### ISSUE TITLE
Existing projects are not visible in the latest version

### ISSUE THREAD

**Issue by krishnaram-nayanar** [jarrodek/ChromeRestClient#522]
I am not able to view the projects and history which was saved in the old version.
I am also not able to import the projects also.
Please advice, there are lot of urls saved which I am not able to use now.

**Comment by jarrodek** [comment]
Thanks for issue report. You are the first one on that matter :)

In the left nav panel you have dropdown menu on the bottom. Can you paste error logs from logs viewer after restarting the app? It appears there is a datastore initialization in some cases an I can't reproduce the problem. If there is no database errors you can also [debug](https://github.com/jarrodek/ChromeRestClient/wiki/debugging) app. Once you already debugging the app you can also check the "resources" tab in Chrome Dev Tools and check if data is in IndexedDb database.

**Comment by krishnaram-nayanar** [comment]
here are the logs

Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic' because it violates the following Content Security Policy directive: "style-src 'self' blob: filesystem: data: chrome-extension-resource: 'unsafe-inline'".

index.html:1 Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Roboto+Mono:400,700' because it violates the following Content Security Policy directive: "style-src 'self' blob: filesystem: data: chrome-extension-resource: 'unsafe-inline'".

elements.js:7624 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
elements.js:7625 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
elements.js:14774 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
app.logger.js:59 Not signed in to chrome.
app.logger.js:59 _requestChanged RequestLocalObject {url: "", method: "GET", headers: "", payload: undefined, isSaved: false…}
app.logger.js:59 Database already populated
app.logger.js:59 The database has been populated with data.
app.logger.js:59 Database already populated
app.logger.js:59 The database has been populated with data.
app.logger.js:59 Cleared: 6 logs
app.logger.js:59 arc-data-import::_importFileReady::JSON.parse::error SyntaxError: Unexpected token N
    at Object.parse (native)
    at arc-file-importer.Polymer._importFileReady (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:57264:27)
    at file-reader.handler (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:3323:17)
    at file-reader.Polymer.Base._addFeature.fire (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:4079:6)
    at file-reader.Polymer._readResult (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:22857:12)console.(anonymous function) @ app.logger.js:59Polymer._importFileReady @ elements.js:57290handler @ elements.js:3323Polymer.Base._addFeature.fire @ elements.js:4079Polymer._readResult @ elements.js:22857

**Comment by krishnaram-nayanar** [comment]
Thank you for the support.
I have resolved the issue.
There was some invalid projects in the json file.I have removed that and got imported.
{"id":9, "name":"[object Object]", "created":NaN},{"id":10, "name":"[object Object]", "created":NaN},{"id":11, "name":"[object Object]", "created":NaN}

**Comment by jarrodek** [comment]
There is however issue in the file exporter which causing such error.
Thank you for the logs!

**Comment by jarrodek** [comment]
I can't reproduce the issue anymore. It might be already fixed with previous bug fixes

**Comment by TobbeD** [comment]
Still a problem for me. What to do?
/T
Den 28 apr 2016 18:11 skrev "Paweł Psztyć" <notifications@github.com>:
>
> I can't reproduce the issue anymore. It might be already fixed with
previous bug fixes

**Comment by jarrodek** [comment]
@TobbeD can you try export data from the app? Ad can you see it your requests data are there?
